void printarray(int *a, int len);
void bubblesortt(char **a, int len);
void selectionSort(int *a, int len);
void insertionSort(int *a, int len);
void insertionSort2(int *a, int len);
int partition (int *a, int l, int h);
int partition2(int *a, int l, int h);
void quicksortt(int *a, int l, int h);
void quicksortexec(int *a, int l, int  h);
void mergeme(int *a, int start, int mid, int end);
void mergesortt(int *a, int start, int end);
void mergesortexec (int *a, int len);
void heapsortexec(int *a, int len);
void countingsort(int *a,int len);
